apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-butterfly
spec:
  displayName: Butterfly-shell
  author:
    name: shell
    website: "https://blog.ning.moe"
  description: "一个由 shell 定制优化的 Butterfly 🦋 主题"
  logo: "https://halo.run/logo"
  website: "https://blog.ning.moe"
  repo: "https://github.com/biliblihuorong/halo-theme-butterfly.git"
  settingName: theme-butterfly-setting
  configMapName: theme-butterfly-configMap
  version: 2.1.4
  require: 2.0.0
  customTemplates:
    page:
      - name: "友情链接 (Links)"
        file: links.html
      - name: "瞬间 (Moments)"
        file: moments.html
      - name: "相册 (Photos)"
        file: photos.html
      - name: "归档 (Archives)"
        file: archives.html
      - name: "分类列表 (Categories)"
        file: categories.html
      - name: "标签列表 (Tags)"
        file: tags.html
